### ISSUE TITLE
what's the license?

### ISSUE THREAD

**Issue by m0dE** [uigywnkiub/react-chatgpt-clone#1]
hi, thanks for the repo!
can you plz provide license?

**Comment by uigywnkiub** [comment]
> hi, thanks for the repo! can you plz provide license?

Why do you need it for?
I will include one of the licenses.

**Comment by m0dE** [comment]
awesome! thanks. I'm using it for my project https://github.com/m0dE/fullmetal-chat-example

**Comment by uigywnkiub** [comment]
> awesome! thanks. I'm using it for my project https://github.com/m0dE/fullmetal-chat-example

Alright, I wish you all the best!
